version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: dante01yoon/vite-audio:web
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
    stdin_open: true
